export enum LW_ACTION_TYPE {
  LOAD_ACTION_CHART = "LOAD_ACTION_CHART",
  LOAD_ACTION_CHART_SUCCESS = "LOAD_ACTION_CHART_SUCCESS",
  TAKE_DAMAGE = "TAKE_DAMAGE",
  TOGGLE_LOADING = "TOGGLE_LOADING"
}

export interface ILwAction {
  type: LW_ACTION_TYPE;
  payload: any;
}
